services:
    front:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: nextjs
        ports:
            - "3000:3000"
        restart: unless-stopped
        depends_on:
            - mysql

    mysql:
        image: mysql:9.3
        container_name: mysql
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=eco-service-db
            - MYSQL_USER=eco-service-user
            - MYSQL_PASSWORD=eco-service-password
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql-volume:/var/lib/mysql
            - ./prisma/sql/setup-prod.sql:/docker-entrypoint-initdb.d/setup-prod.sql
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 60s

volumes:
    mysql-volume:
        name: data
