import PrismaInstance from "@lib/prisma";
import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";
import { cacheLifeApi, hashParamsForCacheKey } from "@utils/FetchConfig";
import { unstable_cacheLife as cacheLife, unstable_cacheTag as cacheTag } from "next/cache";

/**
 * # Content Cached Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/cached/{{model}}Cached.hbs` as base template
 * - to generate cached function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type ContentFindFirstProps<T extends Prisma.ContentFindFirstArgs> = Prisma.SelectSubset<T, Prisma.ContentFindFirstArgs>;
type ContentFindFirstResponse<T extends Prisma.ContentFindFirstArgs> = GetResult<
    Prisma.$ContentPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type ContentFindUniqueProps<T extends Prisma.ContentFindUniqueArgs> = Prisma.SelectSubset<
    T,
    Prisma.ContentFindUniqueArgs
>;
type ContentFindUniqueResponse<T extends Prisma.ContentFindUniqueArgs> = GetResult<
    Prisma.$ContentPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type ContentFindManyProps<T extends Prisma.ContentFindManyArgs> = Prisma.SelectSubset<T, Prisma.ContentFindManyArgs>;
type ContentFindManyResponse<T extends Prisma.ContentFindManyArgs> = GetResult<
    Prisma.$ContentPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type ContentCountProps<T extends Prisma.ContentCountArgs> = Prisma.SelectSubset<T, Prisma.ContentCountArgs>;
type ContentCountResponse<T extends Prisma.ContentCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.ContentCountAggregateOutputType>
        : number;

// ========== Services ========== //

export const ContentFindFirstCached = async <T extends Prisma.ContentFindFirstArgs>(
    params: ContentFindFirstProps<T>,
): Promise<ContentFindFirstResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All content services
        "content",
        // All findFirst services
        "findFirst",
        // All content findFirst services
        "content-findFirst",
        // This specific services
        hashParamsForCacheKey("content-findFirst", params),
    );

    return PrismaInstance.content.findFirst(params);
};

export const ContentFindUniqueCached = async <T extends Prisma.ContentFindUniqueArgs>(
    params: ContentFindUniqueProps<T>,
): Promise<ContentFindUniqueResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All content services
        "content",
        // All findUnique services
        "findUnique",
        // All content findUnique services
        "content-findUnique",
        // This specific services
        hashParamsForCacheKey("content-findUnique", params),
    );

    return PrismaInstance.content.findUnique(params);
};

export const ContentFindManyCached = async <T extends Prisma.ContentFindManyArgs>(
    params: ContentFindManyProps<T>,
): Promise<ContentFindManyResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All content services
        "content",
        // All findMany services
        "findMany",
        // All content findMany services
        "content-findMany",
        // This specific services
        hashParamsForCacheKey("content-findMany", params),
    );

    return PrismaInstance.content.findMany(params);
};

export const ContentCountCached = async <T extends Prisma.ContentCountArgs>(
    params: ContentCountProps<T>,
): Promise<ContentCountResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All content services
        "content",
        // All count services
        "count",
        // All content count services
        "content-count",
        // This specific services
        hashParamsForCacheKey("content-count", params),
    );

    return PrismaInstance.content.count(params);
};
