import ProductService from "@class/ProductClass";
import { Prisma } from "@prisma/client";
import {
    ProductCountProps,
    ProductCountResponse,
    ProductFindFirstProps,
    ProductFindFirstResponse,
    ProductFindManyProps,
    ProductFindManyResponse,
    ProductFindUniqueProps,
    ProductFindUniqueResponse,
} from "@services/types";
import { cacheLifeApi, hashParamsForCacheKey } from "@utils/FetchConfig";
import { unstable_cacheLife as cacheLife, unstable_cacheTag as cacheTag } from "next/cache";

/**
 * # Product Cached Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/cached/{{model}}Cached.hbs` as base template
 * - to generate cached function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Services ========== //

export const ProductFindFirstCached = async <T extends Prisma.ProductFindFirstArgs>(
    params: ProductFindFirstProps<T>,
): Promise<ProductFindFirstResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All product services
        "product",
        // All findFirst services
        "findFirst",
        // All product findFirst services
        "product-findFirst",
        // This specific services
        hashParamsForCacheKey("product-findFirst", params),
    );

    return await ProductService.findFirst(params);
};

export const ProductFindUniqueCached = async <T extends Prisma.ProductFindUniqueArgs>(
    params: ProductFindUniqueProps<T>,
): Promise<ProductFindUniqueResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All product services
        "product",
        // All findUnique services
        "findUnique",
        // All product findUnique services
        "product-findUnique",
        // This specific services
        hashParamsForCacheKey("product-findUnique", params),
    );

    return await ProductService.findUnique(params);
};

export const ProductFindManyCached = async <T extends Prisma.ProductFindManyArgs>(
    params: ProductFindManyProps<T>,
): Promise<ProductFindManyResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All product services
        "product",
        // All findMany services
        "findMany",
        // All product findMany services
        "product-findMany",
        // This specific services
        hashParamsForCacheKey("product-findMany", params),
    );

    return await ProductService.findMany(params);
};

export const ProductCountCached = async <T extends Prisma.ProductCountArgs>(
    params: ProductCountProps<T>,
): Promise<ProductCountResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All product services
        "product",
        // All count services
        "count",
        // All product count services
        "product-count",
        // This specific services
        hashParamsForCacheKey("product-count", params),
    );

    return await ProductService.count(params);
};
