services:
    mysql:
        ports:
            - "3307:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
            interval: 2s
            timeout: 1s
            retries: 30
            start_period: 10s

    nextjs:
        profiles: ["disabled"]
