####################
#       Base       #
####################
FROM node:18-alpine3.21 AS base
WORKDIR /app

# Install pnpm and MySQL client
RUN npm install -g pnpm
RUN apk add --no-cache mysql-client mariadb-connector-c

####################
#   Dependencies   #
####################
FROM base AS deps

# Import packages and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

####################
#    Development   #
####################
FROM base AS dev

# Import packages, dependencies and Prisma schema
COPY package.json pnpm-lock.yaml ./
COPY --from=deps /app/node_modules ./node_modules
COPY prisma/schema.prisma ./prisma/schema.prisma

# Generate Prisma client
RUN pnpm run prisma:generate

####################
#    Run server    #
####################
CMD ["/bin/sh", "-c", "\
    pnpm run db:reload --docker && \
    pnpm run prisma:deploy && \
    pnpm run fixtures:reload && \
    pnpm run dev \
"]
