####################
#       Base       #
####################
FROM node:18-alpine3.21 AS base
WORKDIR /app

# Override environment file (useless here, but for consistency)
COPY .env.dev ./.env

# Install pnpm and MySQL client
RUN npm install -g pnpm
RUN apk add --no-cache mysql-client mariadb-connector-c

####################
#   Dependencies   #
####################
FROM base AS deps

# Import packages and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

####################
#    Development   #
####################
FROM deps AS dev

# Import Prisma schema
COPY prisma/schema.prisma ./prisma/schema.prisma

# Generate Prisma client
RUN pnpm run prisma:generate

####################
#    Run server    #
####################
CMD ["/bin/sh", "-c", "\
    pnpm run db:reload --docker && \
    pnpm run prisma:deploy && \
    pnpm run fixtures:reload && \
    pnpm run dev \
"]
