import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";
import {
    PrismaClientKnownRequestError,
    PrismaClientUnknownRequestError,
    PrismaClientValidationError,
} from "@prisma/client/runtime/library";
import { FruitCountCached, FruitFindFirstCached, FruitFindManyCached, FruitFindUniqueCached } from "@services/cached";

/**
 * # Fruit Server Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/server/{{model}}Server.hbs` as base template
 * - to generate server function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type FruitFindFirstProps<T extends Prisma.FruitFindFirstArgs> = Prisma.SelectSubset<T, Prisma.FruitFindFirstArgs>;
type FruitFindFirstResponse<T extends Prisma.FruitFindFirstArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type FruitFindUniqueProps<T extends Prisma.FruitFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.FruitFindUniqueArgs>;
type FruitFindUniqueResponse<T extends Prisma.FruitFindUniqueArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type FruitFindManyProps<T extends Prisma.FruitFindManyArgs> = Prisma.SelectSubset<T, Prisma.FruitFindManyArgs>;
type FruitFindManyResponse<T extends Prisma.FruitFindManyArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type FruitCountProps<T extends Prisma.FruitCountArgs> = Prisma.SelectSubset<T, Prisma.FruitCountArgs>;
type FruitCountResponse<T extends Prisma.FruitCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.FruitCountAggregateOutputType>
        : number;

// ========== Services ========== //

export const FruitFindFirstServer = async <T extends Prisma.FruitFindFirstArgs>(
    params: FruitFindFirstProps<T>,
): Promise<FruitFindFirstResponse<T>> => {
    try {
        const response = await FruitFindFirstCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Fruit", "findFirst", error);
    }
};

export const FruitFindUniqueServer = async <T extends Prisma.FruitFindUniqueArgs>(
    params: FruitFindUniqueProps<T>,
): Promise<FruitFindUniqueResponse<T>> => {
    try {
        const response = await FruitFindUniqueCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Fruit", "findUnique", error);
    }
};

export const FruitFindManyServer = async <T extends Prisma.FruitFindManyArgs>(
    params: FruitFindManyProps<T>,
): Promise<FruitFindManyResponse<T>> => {
    try {
        const response = await FruitFindManyCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Fruit", "findMany", error);
    }
};

export const FruitCountServer = async <T extends Prisma.FruitCountArgs>(
    params: FruitCountProps<T>,
): Promise<FruitCountResponse<T>> => {
    try {
        const response = await FruitCountCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Fruit", "count", error);
    }
};

// ========== Error Handling ========== //

const ServiceError = (serviceName: string, methodName: string, error: unknown) => {
    if (process.env.NODE_ENV === "development") {
        const message = (error as Error).message;

        const isPrismaError =
            error instanceof PrismaClientKnownRequestError ||
            error instanceof PrismaClientUnknownRequestError ||
            error instanceof PrismaClientValidationError;

        if (isPrismaError) {
            const prismaMessage = serviceName + " -> " + methodName + " -> Prisma error -> " + message;
            console.error(prismaMessage);
            throw new Error(prismaMessage);
        } else {
            const errorMessage = serviceName + " -> " + methodName + " -> " + message;
            console.error(errorMessage);
            throw new Error(errorMessage);
        }
    }

    // TODO: add logging
    throw new Error("Something went wrong...");
};
