import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";
import {
    PrismaClientKnownRequestError,
    PrismaClientUnknownRequestError,
    PrismaClientValidationError,
} from "@prisma/client/runtime/library";
import { OrderCountCached, OrderFindFirstCached, OrderFindManyCached, OrderFindUniqueCached } from "@services/cached";

/**
 * # Order Server Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/server/{{model}}Server.hbs` as base template
 * - to generate server function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type OrderFindFirstProps<T extends Prisma.OrderFindFirstArgs> = Prisma.SelectSubset<T, Prisma.OrderFindFirstArgs>;
type OrderFindFirstResponse<T extends Prisma.OrderFindFirstArgs> = GetResult<
    Prisma.$OrderPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type OrderFindUniqueProps<T extends Prisma.OrderFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.OrderFindUniqueArgs>;
type OrderFindUniqueResponse<T extends Prisma.OrderFindUniqueArgs> = GetResult<
    Prisma.$OrderPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type OrderFindManyProps<T extends Prisma.OrderFindManyArgs> = Prisma.SelectSubset<T, Prisma.OrderFindManyArgs>;
type OrderFindManyResponse<T extends Prisma.OrderFindManyArgs> = GetResult<
    Prisma.$OrderPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type OrderCountProps<T extends Prisma.OrderCountArgs> = Prisma.SelectSubset<T, Prisma.OrderCountArgs>;
type OrderCountResponse<T extends Prisma.OrderCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.OrderCountAggregateOutputType>
        : number;

// ========== Services ========== //

export const OrderFindFirstServer = async <T extends Prisma.OrderFindFirstArgs>(
    params: OrderFindFirstProps<T>,
): Promise<OrderFindFirstResponse<T>> => {
    try {
        const response = await OrderFindFirstCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Order", "findFirst", error);
    }
};

export const OrderFindUniqueServer = async <T extends Prisma.OrderFindUniqueArgs>(
    params: OrderFindUniqueProps<T>,
): Promise<OrderFindUniqueResponse<T>> => {
    try {
        const response = await OrderFindUniqueCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Order", "findUnique", error);
    }
};

export const OrderFindManyServer = async <T extends Prisma.OrderFindManyArgs>(
    params: OrderFindManyProps<T>,
): Promise<OrderFindManyResponse<T>> => {
    try {
        const response = await OrderFindManyCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Order", "findMany", error);
    }
};

export const OrderCountServer = async <T extends Prisma.OrderCountArgs>(
    params: OrderCountProps<T>,
): Promise<OrderCountResponse<T>> => {
    try {
        const response = await OrderCountCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Order", "count", error);
    }
};

// ========== Error Handling ========== //

const ServiceError = (serviceName: string, methodName: string, error: unknown) => {
    if (process.env.NODE_ENV === "development") {
        const message = (error as Error).message;

        const isPrismaError =
            error instanceof PrismaClientKnownRequestError ||
            error instanceof PrismaClientUnknownRequestError ||
            error instanceof PrismaClientValidationError;

        if (isPrismaError) {
            const prismaMessage = serviceName + " -> " + methodName + " -> Prisma error -> " + message;
            console.error(prismaMessage);
            throw new Error(prismaMessage);
        } else {
            const errorMessage = serviceName + " -> " + methodName + " -> " + message;
            console.error(errorMessage);
            throw new Error(errorMessage);
        }
    }

    // TODO: add logging
    throw new Error("Something went wrong...");
};
