import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";
import {
    PrismaClientKnownRequestError,
    PrismaClientUnknownRequestError,
    PrismaClientValidationError,
} from "@prisma/client/runtime/library";
import {
    VerificationCountCached,
    VerificationFindFirstCached,
    VerificationFindManyCached,
    VerificationFindUniqueCached,
} from "@services/cached";

/**
 * # Verification Server Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/server/{{model}}Server.hbs` as base template
 * - to generate server function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type VerificationFindFirstProps<T extends Prisma.VerificationFindFirstArgs> = Prisma.SelectSubset<
    T,
    Prisma.VerificationFindFirstArgs
>;
type VerificationFindFirstResponse<T extends Prisma.VerificationFindFirstArgs> = GetResult<
    Prisma.$VerificationPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type VerificationFindUniqueProps<T extends Prisma.VerificationFindUniqueArgs> = Prisma.SelectSubset<
    T,
    Prisma.VerificationFindUniqueArgs
>;
type VerificationFindUniqueResponse<T extends Prisma.VerificationFindUniqueArgs> = GetResult<
    Prisma.$VerificationPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type VerificationFindManyProps<T extends Prisma.VerificationFindManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.VerificationFindManyArgs
>;
type VerificationFindManyResponse<T extends Prisma.VerificationFindManyArgs> = GetResult<
    Prisma.$VerificationPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type VerificationCountProps<T extends Prisma.VerificationCountArgs> = Prisma.SelectSubset<
    T,
    Prisma.VerificationCountArgs
>;
type VerificationCountResponse<T extends Prisma.VerificationCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.VerificationCountAggregateOutputType>
        : number;

// ========== Services ========== //

export const VerificationFindFirstServer = async <T extends Prisma.VerificationFindFirstArgs>(
    params: VerificationFindFirstProps<T>,
): Promise<VerificationFindFirstResponse<T>> => {
    try {
        const response = await VerificationFindFirstCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Verification", "findFirst", error);
    }
};

export const VerificationFindUniqueServer = async <T extends Prisma.VerificationFindUniqueArgs>(
    params: VerificationFindUniqueProps<T>,
): Promise<VerificationFindUniqueResponse<T>> => {
    try {
        const response = await VerificationFindUniqueCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Verification", "findUnique", error);
    }
};

export const VerificationFindManyServer = async <T extends Prisma.VerificationFindManyArgs>(
    params: VerificationFindManyProps<T>,
): Promise<VerificationFindManyResponse<T>> => {
    try {
        const response = await VerificationFindManyCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Verification", "findMany", error);
    }
};

export const VerificationCountServer = async <T extends Prisma.VerificationCountArgs>(
    params: VerificationCountProps<T>,
): Promise<VerificationCountResponse<T>> => {
    try {
        const response = await VerificationCountCached(params);
        return response;
    } catch (error) {
        throw ServiceError("Verification", "count", error);
    }
};

// ========== Error Handling ========== //

const ServiceError = (serviceName: string, methodName: string, error: unknown) => {
    if (process.env.NODE_ENV === "development") {
        const message = (error as Error).message;

        const isPrismaError =
            error instanceof PrismaClientKnownRequestError ||
            error instanceof PrismaClientUnknownRequestError ||
            error instanceof PrismaClientValidationError;

        if (isPrismaError) {
            const prismaMessage = serviceName + " -> " + methodName + " -> Prisma error -> " + message;
            console.error(prismaMessage);
            throw new Error(prismaMessage);
        } else {
            const errorMessage = serviceName + " -> " + methodName + " -> " + message;
            console.error(errorMessage);
            throw new Error(errorMessage);
        }
    }

    // TODO: add logging
    throw new Error("Something went wrong...");
};
