# Docker Hybrid Config
# See more: `./docs/installation-guides/hybrid.md`

services:
    mysql:
        image: mysql:9.3
        container_name: mysql
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            # MySQL data (volume)
            - mysql-hybrid-volume:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - nextjs-hybrid-network

    redis:
        image: redis/redis-stack:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379" # Redis server
            - "8001:8001" # Redis dashboard
        volumes:
            - redis-hybrid-volume:/data
        networks:
            - nextjs-hybrid-network

volumes:
    mysql-hybrid-volume:
        driver: local
    redis-hybrid-volume:
        driver: local

networks:
    nextjs-hybrid-network:
        driver: bridge
