# .github/actions/setup-database/action.yml
name: Setup database
description: Setup MySQL database, generate Prisma client, deploy migrations and load fixtures
runs:
    using: "composite"
    steps:
        - name: Grant all privileges
          run: mysql -h 127.0.0.1 -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'eco_service_user'@'%'; GRANT ALL PRIVILEGES ON eco_service_db.* TO 'eco_service_user'@'%'; FLUSH PRIVILEGES;"
          shell: bash
        - name: Generate Prisma client
          run: pnpm prisma:generate
          shell: bash
        - name: Deploy Prisma migrations
          run: pnpm prisma:deploy
          shell: bash
        - name: Install fixtures
          run: pnpm fixtures:setup
          shell: bash