"use server";

import AddressService from "@class/AddressClass";
import { requiresSafeMessage } from "@permissions/requiresSafeMessage";
import { Prisma } from "@prisma/client/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/client";

/**
 * # Address Action Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/actions/{{model}}Action.hbs` as base template
 * - to generate server actions files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Create
type AddressCreateProps<T extends Prisma.AddressCreateArgs> = Prisma.SelectSubset<T, Prisma.AddressCreateArgs>;
type AddressCreateResponse<T extends Prisma.AddressCreateArgs> = GetResult<
    Prisma.$AddressPayload<InternalArgs>,
    T,
    "create",
    PrismaClientOptions
>;

// Upsert
type AddressUpsertProps<T extends Prisma.AddressUpsertArgs> = Prisma.SelectSubset<T, Prisma.AddressUpsertArgs>;
type AddressUpsertResponse<T extends Prisma.AddressUpsertArgs> = GetResult<
    Prisma.$AddressPayload<InternalArgs>,
    T,
    "upsert",
    PrismaClientOptions
>;

// Update
type AddressUpdateProps<T extends Prisma.AddressUpdateArgs> = Prisma.SelectSubset<T, Prisma.AddressUpdateArgs>;
type AddressUpdateResponse<T extends Prisma.AddressUpdateArgs> = GetResult<
    Prisma.$AddressPayload<InternalArgs>,
    T,
    "update",
    PrismaClientOptions
>;

// Delete
type AddressDeleteProps<T extends Prisma.AddressDeleteArgs> = Prisma.SelectSubset<T, Prisma.AddressDeleteArgs>;
type AddressDeleteResponse<T extends Prisma.AddressDeleteArgs> = GetResult<
    Prisma.$AddressPayload<InternalArgs>,
    T,
    "delete",
    PrismaClientOptions
>;

// Create Many
type AddressCreateManyProps<T extends Prisma.AddressCreateManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.AddressCreateManyArgs
>;
type AddressCreateManyResponse = Prisma.BatchPayload;

// Update Many
type AddressUpdateManyProps<T extends Prisma.AddressUpdateManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.AddressUpdateManyArgs
>;
type AddressUpdateManyResponse = Prisma.BatchPayload;

// Delete Many
type AddressDeleteManyProps<T extends Prisma.AddressDeleteManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.AddressDeleteManyArgs
>;
type AddressDeleteManyResponse = Prisma.BatchPayload;

// Find First
type AddressFindFirstProps<T extends Prisma.AddressFindFirstArgs> = Prisma.SelectSubset<T, Prisma.AddressFindFirstArgs>;
type AddressFindFirstResponse<T extends Prisma.AddressFindFirstArgs> = GetResult<
    Prisma.$AddressPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type AddressFindUniqueProps<T extends Prisma.AddressFindUniqueArgs> = Prisma.SelectSubset<
    T,
    Prisma.AddressFindUniqueArgs
>;
type AddressFindUniqueResponse<T extends Prisma.AddressFindUniqueArgs> = GetResult<
    Prisma.$AddressPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type AddressFindManyProps<T extends Prisma.AddressFindManyArgs> = Prisma.SelectSubset<T, Prisma.AddressFindManyArgs>;
type AddressFindManyResponse<T extends Prisma.AddressFindManyArgs> = GetResult<
    Prisma.$AddressPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type AddressCountProps<T extends Prisma.AddressCountArgs> = Prisma.SelectSubset<T, Prisma.AddressCountArgs>;
type AddressCountResponse<T extends Prisma.AddressCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.AddressCountAggregateOutputType>
        : number;

// ========== Services ========== //

/**
 * ## Address Create (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const AddressCreateAction = async <T extends Prisma.AddressCreateArgs>(
    props: AddressCreateProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressCreateResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "AddressCreateAction", "Address", "create");
    return await AddressService.create(props);
};

/**
 * ## Address Upsert (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const AddressUpsertAction = async <T extends Prisma.AddressUpsertArgs>(
    props: AddressUpsertProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressUpsertResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "AddressUpsertAction", "Address", "upsert");
    return await AddressService.upsert(props);
};

/**
 * ## Address Update (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const AddressUpdateAction = async <T extends Prisma.AddressUpdateArgs>(
    props: AddressUpdateProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressUpdateResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "AddressUpdateAction", "Address", "update");
    return await AddressService.update(props);
};

/**
 * ## Address Delete (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const AddressDeleteAction = async <T extends Prisma.AddressDeleteArgs>(
    props: AddressDeleteProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressDeleteResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "AddressDeleteAction", "Address", "delete");
    return await AddressService.delete(props);
};

/**
 * ## Address Create Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const AddressCreateManyAction = async <T extends Prisma.AddressCreateManyArgs>(
    props: AddressCreateManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressCreateManyResponse> => {
    await requiresSafeMessage(disableSafeMessage, "AddressCreateManyAction", "Address", "createMany");
    return await AddressService.createMany(props);
};

/**
 * ## Address Update Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const AddressUpdateManyAction = async <T extends Prisma.AddressUpdateManyArgs>(
    props: AddressUpdateManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressUpdateManyResponse> => {
    await requiresSafeMessage(disableSafeMessage, "AddressUpdateManyAction", "Address", "updateMany");
    return await AddressService.updateMany(props);
};

/**
 * ## Address Delete Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const AddressDeleteManyAction = async <T extends Prisma.AddressDeleteManyArgs>(
    props: AddressDeleteManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressDeleteManyResponse> => {
    await requiresSafeMessage(disableSafeMessage, "AddressDeleteManyAction", "Address", "deleteMany");
    return await AddressService.deleteMany(props);
};

/**
 * ## Address Find First (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const AddressFindFirstAction = async <T extends Prisma.AddressFindFirstArgs>(
    props: AddressFindFirstProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressFindFirstResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "AddressFindFirstAction", "Address", "findFirst");
    return await AddressService.findFirst(props);
};

/**
 * ## Address Find Unique (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const AddressFindUniqueAction = async <T extends Prisma.AddressFindUniqueArgs>(
    props: AddressFindUniqueProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressFindUniqueResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "AddressFindUniqueAction", "Address", "findUnique");
    return await AddressService.findUnique(props);
};

/**
 * ## Address Find Many (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const AddressFindManyAction = async <T extends Prisma.AddressFindManyArgs>(
    props: AddressFindManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressFindManyResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "AddressFindManyAction", "Address", "findMany");
    return await AddressService.findMany(props);
};

/**
 * ## Address Count (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const AddressCountAction = async <T extends Prisma.AddressCountArgs>(
    props: AddressCountProps<T>,
    disableSafeMessage: boolean = false,
): Promise<AddressCountResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "AddressCountAction", "Address", "count");
    return await AddressService.count(props);
};
