"use server";

import PrismaInstance from "@lib/prisma";
import { requiresSafeMessage } from "@permissions/requiresSafeMessage";
import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";

/**
 * # Category Action Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/actions/{{model}}Action.hbs` as base template
 * - to generate server actions files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Create
type CategoryCreateProps<T extends Prisma.CategoryCreateArgs> = Prisma.SelectSubset<T, Prisma.CategoryCreateArgs>;
type CategoryCreateResponse<T extends Prisma.CategoryCreateArgs> = GetResult<
    Prisma.$CategoryPayload<InternalArgs>,
    T,
    "create",
    PrismaClientOptions
>;

// Upsert
type CategoryUpsertProps<T extends Prisma.CategoryUpsertArgs> = Prisma.SelectSubset<T, Prisma.CategoryUpsertArgs>;
type CategoryUpsertResponse<T extends Prisma.CategoryUpsertArgs> = GetResult<
    Prisma.$CategoryPayload<InternalArgs>,
    T,
    "upsert",
    PrismaClientOptions
>;

// Update
type CategoryUpdateProps<T extends Prisma.CategoryUpdateArgs> = Prisma.SelectSubset<T, Prisma.CategoryUpdateArgs>;
type CategoryUpdateResponse<T extends Prisma.CategoryUpdateArgs> = GetResult<
    Prisma.$CategoryPayload<InternalArgs>,
    T,
    "update",
    PrismaClientOptions
>;

// Delete
type CategoryDeleteProps<T extends Prisma.CategoryDeleteArgs> = Prisma.SelectSubset<T, Prisma.CategoryDeleteArgs>;
type CategoryDeleteResponse<T extends Prisma.CategoryDeleteArgs> = GetResult<
    Prisma.$CategoryPayload<InternalArgs>,
    T,
    "delete",
    PrismaClientOptions
>;

// Create Many
type CategoryCreateManyProps<T extends Prisma.CategoryCreateManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.CategoryCreateManyArgs
>;
type CategoryCreateManyResponse = Prisma.BatchPayload;

// Update Many
type CategoryUpdateManyProps<T extends Prisma.CategoryUpdateManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.CategoryUpdateManyArgs
>;
type CategoryUpdateManyResponse = Prisma.BatchPayload;

// Delete Many
type CategoryDeleteManyProps<T extends Prisma.CategoryDeleteManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.CategoryDeleteManyArgs
>;
type CategoryDeleteManyResponse = Prisma.BatchPayload;

// Find First
type CategoryFindFirstProps<T extends Prisma.CategoryFindFirstArgs> = Prisma.SelectSubset<
    T,
    Prisma.CategoryFindFirstArgs
>;
type CategoryFindFirstResponse<T extends Prisma.CategoryFindFirstArgs> = GetResult<
    Prisma.$CategoryPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type CategoryFindUniqueProps<T extends Prisma.CategoryFindUniqueArgs> = Prisma.SelectSubset<
    T,
    Prisma.CategoryFindUniqueArgs
>;
type CategoryFindUniqueResponse<T extends Prisma.CategoryFindUniqueArgs> = GetResult<
    Prisma.$CategoryPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type CategoryFindManyProps<T extends Prisma.CategoryFindManyArgs> = Prisma.SelectSubset<T, Prisma.CategoryFindManyArgs>;
type CategoryFindManyResponse<T extends Prisma.CategoryFindManyArgs> = GetResult<
    Prisma.$CategoryPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type CategoryCountProps<T extends Prisma.CategoryCountArgs> = Prisma.SelectSubset<T, Prisma.CategoryCountArgs>;
type CategoryCountResponse<T extends Prisma.CategoryCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.CategoryCountAggregateOutputType>
        : number;

// ========== Services ========== //

/**
 * ## Category Create (Server Action)
 */
export const CategoryCreateAction = async <T extends Prisma.CategoryCreateArgs>(
    props: CategoryCreateProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryCreateResponse<T>> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryCreateAction", "Category", "create");
        const response = await PrismaInstance.category.create(props);
        return response;
    } catch (error) {
        throw new Error("CategoryCreateAction -> " + (error as Error).message);
    }
};

/**
 * ## Category Upsert (Server Action)
 */
export const CategoryUpsertAction = async <T extends Prisma.CategoryUpsertArgs>(
    props: CategoryUpsertProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryUpsertResponse<T>> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryUpsertAction", "Category", "upsert");
        const response = await PrismaInstance.category.upsert(props);
        return response;
    } catch (error) {
        throw new Error("CategoryUpsertAction -> " + (error as Error).message);
    }
};

/**
 * ## Category Update (Server Action)
 */
export const CategoryUpdateAction = async <T extends Prisma.CategoryUpdateArgs>(
    props: CategoryUpdateProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryUpdateResponse<T>> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryUpdateAction", "Category", "update");
        const response = await PrismaInstance.category.update(props);
        return response;
    } catch (error) {
        throw new Error("CategoryUpdateAction -> " + (error as Error).message);
    }
};

/**
 * ## Category Delete (Server Action)
 */
export const CategoryDeleteAction = async <T extends Prisma.CategoryDeleteArgs>(
    props: CategoryDeleteProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryDeleteResponse<T>> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryDeleteAction", "Category", "delete");
        const response = await PrismaInstance.category.delete(props);
        return response;
    } catch (error) {
        throw new Error("CategoryDeleteAction -> " + (error as Error).message);
    }
};

/**
 * ## Category Create Many (Server Action)
 */
export const CategoryCreateManyAction = async <T extends Prisma.CategoryCreateManyArgs>(
    props: CategoryCreateManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryCreateManyResponse> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryCreateManyAction", "Category", "createMany");
        const response = await PrismaInstance.category.createMany(props);
        return response;
    } catch (error) {
        throw new Error("CategoryCreateManyAction -> " + (error as Error).message);
    }
};

/**
 * ## Category Update Many (Server Action)
 */
export const CategoryUpdateManyAction = async <T extends Prisma.CategoryUpdateManyArgs>(
    props: CategoryUpdateManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryUpdateManyResponse> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryUpdateManyAction", "Category", "updateMany");
        const response = await PrismaInstance.category.updateMany(props);
        return response;
    } catch (error) {
        throw new Error("CategoryUpdateManyAction -> " + (error as Error).message);
    }
};

/**
 * ## Category Delete Many (Server Action)
 */
export const CategoryDeleteManyAction = async <T extends Prisma.CategoryDeleteManyArgs>(
    props: CategoryDeleteManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryDeleteManyResponse> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryDeleteManyAction", "Category", "deleteMany");
        const response = await PrismaInstance.category.deleteMany(props);
        return response;
    } catch (error) {
        throw new Error("CategoryDeleteManyAction -> " + (error as Error).message);
    }
};

/**
 * ## Category Find First (Server Action)
 * **WARNING**: Server actions can't be cached and parallelized
 * - Do not use this for fetching data, use API routes with caching instead
 * - But you can use it to get fresh data, without any cache
 */
export const CategoryFindFirstAction = async <T extends Prisma.CategoryFindFirstArgs>(
    props: CategoryFindFirstProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryFindFirstResponse<T>> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryFindFirstAction", "Category", "findFirst");
        const response = await PrismaInstance.category.findFirst(props);
        return response;
    } catch (error) {
        throw new Error("CategoryFindFirstAction -> " + (error as Error).message);
    }
};

/**
 * ## Category Find Unique (Server Action)
 * **WARNING**: Server actions can't be cached and parallelized
 * - Do not use this for fetching data, use API routes with caching instead
 * - But you can use it to get fresh data, without any cache
 */
export const CategoryFindUniqueAction = async <T extends Prisma.CategoryFindUniqueArgs>(
    props: CategoryFindUniqueProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryFindUniqueResponse<T>> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryFindUniqueAction", "Category", "findUnique");
        const response = await PrismaInstance.category.findUnique(props);
        return response;
    } catch (error) {
        throw new Error("CategoryFindUniqueAction -> " + (error as Error).message);
    }
};

/**
 * ## Category Find Many (Server Action)
 * **WARNING**: Server actions can't be cached and parallelized
 * - Do not use this for fetching data, use API routes with caching instead
 * - But you can use it to get fresh data, without any cache
 */
export const CategoryFindManyAction = async <T extends Prisma.CategoryFindManyArgs>(
    props: CategoryFindManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryFindManyResponse<T>> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryFindManyAction", "Category", "findMany");
        const response = await PrismaInstance.category.findMany(props);
        return response;
    } catch (error) {
        throw new Error("CategoryFindManyAction -> " + (error as Error).message);
    }
};

/**
 * ## Category Count (Server Action)
 * **WARNING**: Server actions can't be cached and parallelized
 * - Do not use this for fetching data, use API routes with caching instead
 * - But you can use it to get fresh data, without any cache
 */
export const CategoryCountAction = async <T extends Prisma.CategoryCountArgs>(
    props: CategoryCountProps<T>,
    disableSafeMessage: boolean = false,
): Promise<CategoryCountResponse<T>> => {
    try {
        await requiresSafeMessage(disableSafeMessage, "CategoryCountAction", "Category", "count");
        const response = await PrismaInstance.category.count(props);
        return response;
    } catch (error) {
        throw new Error("CategoryCountAction -> " + (error as Error).message);
    }
};
