"use server";

import DiyService from "@class/DiyClass";
import { requiresSafeMessage } from "@permissions/requiresSafeMessage";
import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";

/**
 * # Diy Action Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/actions/{{model}}Action.hbs` as base template
 * - to generate server actions files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Create
type DiyCreateProps<T extends Prisma.DiyCreateArgs> = Prisma.SelectSubset<T, Prisma.DiyCreateArgs>;
type DiyCreateResponse<T extends Prisma.DiyCreateArgs> = GetResult<
    Prisma.$DiyPayload<InternalArgs>,
    T,
    "create",
    PrismaClientOptions
>;

// Upsert
type DiyUpsertProps<T extends Prisma.DiyUpsertArgs> = Prisma.SelectSubset<T, Prisma.DiyUpsertArgs>;
type DiyUpsertResponse<T extends Prisma.DiyUpsertArgs> = GetResult<
    Prisma.$DiyPayload<InternalArgs>,
    T,
    "upsert",
    PrismaClientOptions
>;

// Update
type DiyUpdateProps<T extends Prisma.DiyUpdateArgs> = Prisma.SelectSubset<T, Prisma.DiyUpdateArgs>;
type DiyUpdateResponse<T extends Prisma.DiyUpdateArgs> = GetResult<
    Prisma.$DiyPayload<InternalArgs>,
    T,
    "update",
    PrismaClientOptions
>;

// Delete
type DiyDeleteProps<T extends Prisma.DiyDeleteArgs> = Prisma.SelectSubset<T, Prisma.DiyDeleteArgs>;
type DiyDeleteResponse<T extends Prisma.DiyDeleteArgs> = GetResult<
    Prisma.$DiyPayload<InternalArgs>,
    T,
    "delete",
    PrismaClientOptions
>;

// Create Many
type DiyCreateManyProps<T extends Prisma.DiyCreateManyArgs> = Prisma.SelectSubset<T, Prisma.DiyCreateManyArgs>;
type DiyCreateManyResponse = Prisma.BatchPayload;

// Update Many
type DiyUpdateManyProps<T extends Prisma.DiyUpdateManyArgs> = Prisma.SelectSubset<T, Prisma.DiyUpdateManyArgs>;
type DiyUpdateManyResponse = Prisma.BatchPayload;

// Delete Many
type DiyDeleteManyProps<T extends Prisma.DiyDeleteManyArgs> = Prisma.SelectSubset<T, Prisma.DiyDeleteManyArgs>;
type DiyDeleteManyResponse = Prisma.BatchPayload;

// Find First
type DiyFindFirstProps<T extends Prisma.DiyFindFirstArgs> = Prisma.SelectSubset<T, Prisma.DiyFindFirstArgs>;
type DiyFindFirstResponse<T extends Prisma.DiyFindFirstArgs> = GetResult<
    Prisma.$DiyPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type DiyFindUniqueProps<T extends Prisma.DiyFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.DiyFindUniqueArgs>;
type DiyFindUniqueResponse<T extends Prisma.DiyFindUniqueArgs> = GetResult<
    Prisma.$DiyPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type DiyFindManyProps<T extends Prisma.DiyFindManyArgs> = Prisma.SelectSubset<T, Prisma.DiyFindManyArgs>;
type DiyFindManyResponse<T extends Prisma.DiyFindManyArgs> = GetResult<
    Prisma.$DiyPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type DiyCountProps<T extends Prisma.DiyCountArgs> = Prisma.SelectSubset<T, Prisma.DiyCountArgs>;
type DiyCountResponse<T extends Prisma.DiyCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.DiyCountAggregateOutputType>
        : number;

// ========== Services ========== //

/**
 * ## Diy Create (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const DiyCreateAction = async <T extends Prisma.DiyCreateArgs>(
    props: DiyCreateProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyCreateResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "DiyCreateAction", "Diy", "create");
    return await DiyService.create(props);
};

/**
 * ## Diy Upsert (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const DiyUpsertAction = async <T extends Prisma.DiyUpsertArgs>(
    props: DiyUpsertProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyUpsertResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "DiyUpsertAction", "Diy", "upsert");
    return await DiyService.upsert(props);
};

/**
 * ## Diy Update (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const DiyUpdateAction = async <T extends Prisma.DiyUpdateArgs>(
    props: DiyUpdateProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyUpdateResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "DiyUpdateAction", "Diy", "update");
    return await DiyService.update(props);
};

/**
 * ## Diy Delete (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const DiyDeleteAction = async <T extends Prisma.DiyDeleteArgs>(
    props: DiyDeleteProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyDeleteResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "DiyDeleteAction", "Diy", "delete");
    return await DiyService.delete(props);
};

/**
 * ## Diy Create Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const DiyCreateManyAction = async <T extends Prisma.DiyCreateManyArgs>(
    props: DiyCreateManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyCreateManyResponse> => {
    await requiresSafeMessage(disableSafeMessage, "DiyCreateManyAction", "Diy", "createMany");
    return await DiyService.createMany(props);
};

/**
 * ## Diy Update Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const DiyUpdateManyAction = async <T extends Prisma.DiyUpdateManyArgs>(
    props: DiyUpdateManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyUpdateManyResponse> => {
    await requiresSafeMessage(disableSafeMessage, "DiyUpdateManyAction", "Diy", "updateMany");
    return await DiyService.updateMany(props);
};

/**
 * ## Diy Delete Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const DiyDeleteManyAction = async <T extends Prisma.DiyDeleteManyArgs>(
    props: DiyDeleteManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyDeleteManyResponse> => {
    await requiresSafeMessage(disableSafeMessage, "DiyDeleteManyAction", "Diy", "deleteMany");
    return await DiyService.deleteMany(props);
};

/**
 * ## Diy Find First (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const DiyFindFirstAction = async <T extends Prisma.DiyFindFirstArgs>(
    props: DiyFindFirstProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyFindFirstResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "DiyFindFirstAction", "Diy", "findFirst");
    return await DiyService.findFirst(props);
};

/**
 * ## Diy Find Unique (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const DiyFindUniqueAction = async <T extends Prisma.DiyFindUniqueArgs>(
    props: DiyFindUniqueProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyFindUniqueResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "DiyFindUniqueAction", "Diy", "findUnique");
    return await DiyService.findUnique(props);
};

/**
 * ## Diy Find Many (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const DiyFindManyAction = async <T extends Prisma.DiyFindManyArgs>(
    props: DiyFindManyProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyFindManyResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "DiyFindManyAction", "Diy", "findMany");
    return await DiyService.findMany(props);
};

/**
 * ## Diy Count (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const DiyCountAction = async <T extends Prisma.DiyCountArgs>(
    props: DiyCountProps<T>,
    disableSafeMessage: boolean = false,
): Promise<DiyCountResponse<T>> => {
    await requiresSafeMessage(disableSafeMessage, "DiyCountAction", "Diy", "count");
    return await DiyService.count(props);
};
