import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";
import {
    ArticleCountCached,
    ArticleFindFirstCached,
    ArticleFindManyCached,
    ArticleFindUniqueCached,
} from "@services/cached";
import { ResponseFormat, parseAndDecodeParams } from "@utils/FetchConfig";
import { NextRequest, NextResponse } from "next/server";

/**
 * # Article Api Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/api/{{model}}Api.hbs` as base template
 * - to generate api function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type ArticleFindFirstProps<T extends Prisma.ArticleFindFirstArgs> = Prisma.SelectSubset<T, Prisma.ArticleFindFirstArgs>;
type ArticleFindFirstResponse<T extends Prisma.ArticleFindFirstArgs> = GetResult<
    Prisma.$ArticlePayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type ArticleFindUniqueProps<T extends Prisma.ArticleFindUniqueArgs> = Prisma.SelectSubset<
    T,
    Prisma.ArticleFindUniqueArgs
>;
type ArticleFindUniqueResponse<T extends Prisma.ArticleFindUniqueArgs> = GetResult<
    Prisma.$ArticlePayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type ArticleFindManyProps<T extends Prisma.ArticleFindManyArgs> = Prisma.SelectSubset<T, Prisma.ArticleFindManyArgs>;
type ArticleFindManyResponse<T extends Prisma.ArticleFindManyArgs> = GetResult<
    Prisma.$ArticlePayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type ArticleCountProps<T extends Prisma.ArticleCountArgs> = Prisma.SelectSubset<T, Prisma.ArticleCountArgs>;
type ArticleCountResponse<T extends Prisma.ArticleCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.ArticleCountAggregateOutputType>
        : number;

// ========== Routes ========== //

type RouteResponse<T> = Promise<NextResponse<ResponseFormat<T>>>;

export type ArticleRoutes<Input> = {
    "/internal/article/findFirst": <T extends Prisma.ArticleFindFirstArgs>() => {
        params: ArticleFindFirstProps<T>;
        response: ArticleFindFirstResponse<Input extends ArticleFindFirstProps<T> ? Input : never>;
    };
    "/internal/article/findUnique": <T extends Prisma.ArticleFindUniqueArgs>() => {
        params: ArticleFindUniqueProps<T>;
        response: ArticleFindUniqueResponse<Input extends ArticleFindUniqueProps<T> ? Input : never>;
    };
    "/internal/article/findMany": <T extends Prisma.ArticleFindManyArgs>() => {
        params: ArticleFindManyProps<T>;
        response: ArticleFindManyResponse<Input extends ArticleFindManyProps<T> ? Input : never>;
    };
    "/internal/article/count": <T extends Prisma.ArticleCountArgs>() => {
        params: ArticleCountProps<T>;
        response: ArticleCountResponse<Input extends ArticleCountProps<T> ? Input : never>;
    };
};

// ========== Services ========== //

export const ArticleFindFirstApi = async <T extends Prisma.ArticleFindFirstArgs>(
    request: NextRequest,
): RouteResponse<ArticleFindFirstResponse<T>> => {
    try {
        const params: ArticleFindFirstProps<T> = parseAndDecodeParams(request);
        const response: ArticleFindFirstResponse<T> = await ArticleFindFirstCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const ArticleFindUniqueApi = async <T extends Prisma.ArticleFindUniqueArgs>(
    request: NextRequest,
): RouteResponse<ArticleFindUniqueResponse<T>> => {
    try {
        const params: ArticleFindUniqueProps<T> = parseAndDecodeParams(request);
        const response: ArticleFindUniqueResponse<T> = await ArticleFindUniqueCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const ArticleFindManyApi = async <T extends Prisma.ArticleFindManyArgs>(
    request: NextRequest,
): RouteResponse<ArticleFindManyResponse<T>> => {
    try {
        const params: ArticleFindManyProps<T> = parseAndDecodeParams(request);
        const response: ArticleFindManyResponse<T> = await ArticleFindManyCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const ArticleCountApi = async <T extends Prisma.ArticleCountArgs>(
    request: NextRequest,
): RouteResponse<ArticleCountResponse<T>> => {
    try {
        const params: ArticleCountProps<T> = parseAndDecodeParams(request);
        const response: ArticleCountResponse<T> = await ArticleCountCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};
