import { Prisma } from "@prisma/client/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/client";
import {
    ContentCountCached,
    ContentFindFirstCached,
    ContentFindManyCached,
    ContentFindUniqueCached,
} from "@services/cached";
import { decodeParams } from "@utils/url-parsers";
import { NextRequest, NextResponse } from "next/server";
import { ResponseFormat } from "@/solid/solid-config";

/**
 * # Content Api Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/api/{{model}}Api.hbs` as base template
 * - to generate api function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type ContentFindFirstProps<T extends Prisma.ContentFindFirstArgs> = Prisma.SelectSubset<T, Prisma.ContentFindFirstArgs>;
type ContentFindFirstResponse<T extends Prisma.ContentFindFirstArgs> = GetResult<
    Prisma.$ContentPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type ContentFindUniqueProps<T extends Prisma.ContentFindUniqueArgs> = Prisma.SelectSubset<
    T,
    Prisma.ContentFindUniqueArgs
>;
type ContentFindUniqueResponse<T extends Prisma.ContentFindUniqueArgs> = GetResult<
    Prisma.$ContentPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type ContentFindManyProps<T extends Prisma.ContentFindManyArgs> = Prisma.SelectSubset<T, Prisma.ContentFindManyArgs>;
type ContentFindManyResponse<T extends Prisma.ContentFindManyArgs> = GetResult<
    Prisma.$ContentPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type ContentCountProps<T extends Prisma.ContentCountArgs> = Prisma.SelectSubset<T, Prisma.ContentCountArgs>;
type ContentCountResponse<T extends Prisma.ContentCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.ContentCountAggregateOutputType>
        : number;

// ========== Routes ========== //

type RouteResponse<T> = Promise<NextResponse<ResponseFormat<T>>>;

export type ContentRoutes<Input> = {
    "/solid/content/findFirst": <T extends Prisma.ContentFindFirstArgs>() => {
        params: ContentFindFirstProps<T>;
        response: ContentFindFirstResponse<Input extends ContentFindFirstProps<T> ? Input : never>;
    };
    "/solid/content/findUnique": <T extends Prisma.ContentFindUniqueArgs>() => {
        params: ContentFindUniqueProps<T>;
        response: ContentFindUniqueResponse<Input extends ContentFindUniqueProps<T> ? Input : never>;
    };
    "/solid/content/findMany": <T extends Prisma.ContentFindManyArgs>() => {
        params: ContentFindManyProps<T>;
        response: ContentFindManyResponse<Input extends ContentFindManyProps<T> ? Input : never>;
    };
    "/solid/content/count": <T extends Prisma.ContentCountArgs>() => {
        params: ContentCountProps<T>;
        response: ContentCountResponse<Input extends ContentCountProps<T> ? Input : never>;
    };
};

// ========== Services ========== //

export const ContentFindFirstApi = async <T extends Prisma.ContentFindFirstArgs>(
    request: NextRequest,
): RouteResponse<ContentFindFirstResponse<T>> => {
    try {
        const params: ContentFindFirstProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: ContentFindFirstResponse<T> = await ContentFindFirstCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const ContentFindUniqueApi = async <T extends Prisma.ContentFindUniqueArgs>(
    request: NextRequest,
): RouteResponse<ContentFindUniqueResponse<T>> => {
    try {
        const params: ContentFindUniqueProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: ContentFindUniqueResponse<T> = await ContentFindUniqueCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const ContentFindManyApi = async <T extends Prisma.ContentFindManyArgs>(
    request: NextRequest,
): RouteResponse<ContentFindManyResponse<T>> => {
    try {
        const params: ContentFindManyProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: ContentFindManyResponse<T> = await ContentFindManyCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const ContentCountApi = async <T extends Prisma.ContentCountArgs>(
    request: NextRequest,
): RouteResponse<ContentCountResponse<T>> => {
    try {
        const params: ContentCountProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: ContentCountResponse<T> = await ContentCountCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};
