import { Prisma } from "@prisma/client/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/client";
import { DiyCountCached, DiyFindFirstCached, DiyFindManyCached, DiyFindUniqueCached } from "@services/cached";
import { decodeParams } from "@utils/url-parsers";
import { NextRequest, NextResponse } from "next/server";
import { ResponseFormat } from "@/solid/solid-config";

/**
 * # Diy Api Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/api/{{model}}Api.hbs` as base template
 * - to generate api function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type DiyFindFirstProps<T extends Prisma.DiyFindFirstArgs> = Prisma.SelectSubset<T, Prisma.DiyFindFirstArgs>;
type DiyFindFirstResponse<T extends Prisma.DiyFindFirstArgs> = GetResult<
    Prisma.$DiyPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type DiyFindUniqueProps<T extends Prisma.DiyFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.DiyFindUniqueArgs>;
type DiyFindUniqueResponse<T extends Prisma.DiyFindUniqueArgs> = GetResult<
    Prisma.$DiyPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type DiyFindManyProps<T extends Prisma.DiyFindManyArgs> = Prisma.SelectSubset<T, Prisma.DiyFindManyArgs>;
type DiyFindManyResponse<T extends Prisma.DiyFindManyArgs> = GetResult<
    Prisma.$DiyPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type DiyCountProps<T extends Prisma.DiyCountArgs> = Prisma.SelectSubset<T, Prisma.DiyCountArgs>;
type DiyCountResponse<T extends Prisma.DiyCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.DiyCountAggregateOutputType>
        : number;

// ========== Routes ========== //

type RouteResponse<T> = Promise<NextResponse<ResponseFormat<T>>>;

export type DiyRoutes<Input> = {
    "/solid/diy/findFirst": <T extends Prisma.DiyFindFirstArgs>() => {
        params: DiyFindFirstProps<T>;
        response: DiyFindFirstResponse<Input extends DiyFindFirstProps<T> ? Input : never>;
    };
    "/solid/diy/findUnique": <T extends Prisma.DiyFindUniqueArgs>() => {
        params: DiyFindUniqueProps<T>;
        response: DiyFindUniqueResponse<Input extends DiyFindUniqueProps<T> ? Input : never>;
    };
    "/solid/diy/findMany": <T extends Prisma.DiyFindManyArgs>() => {
        params: DiyFindManyProps<T>;
        response: DiyFindManyResponse<Input extends DiyFindManyProps<T> ? Input : never>;
    };
    "/solid/diy/count": <T extends Prisma.DiyCountArgs>() => {
        params: DiyCountProps<T>;
        response: DiyCountResponse<Input extends DiyCountProps<T> ? Input : never>;
    };
};

// ========== Services ========== //

export const DiyFindFirstApi = async <T extends Prisma.DiyFindFirstArgs>(
    request: NextRequest,
): RouteResponse<DiyFindFirstResponse<T>> => {
    try {
        const params: DiyFindFirstProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: DiyFindFirstResponse<T> = await DiyFindFirstCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const DiyFindUniqueApi = async <T extends Prisma.DiyFindUniqueArgs>(
    request: NextRequest,
): RouteResponse<DiyFindUniqueResponse<T>> => {
    try {
        const params: DiyFindUniqueProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: DiyFindUniqueResponse<T> = await DiyFindUniqueCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const DiyFindManyApi = async <T extends Prisma.DiyFindManyArgs>(
    request: NextRequest,
): RouteResponse<DiyFindManyResponse<T>> => {
    try {
        const params: DiyFindManyProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: DiyFindManyResponse<T> = await DiyFindManyCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const DiyCountApi = async <T extends Prisma.DiyCountArgs>(
    request: NextRequest,
): RouteResponse<DiyCountResponse<T>> => {
    try {
        const params: DiyCountProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: DiyCountResponse<T> = await DiyCountCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};
