import { Prisma } from "@prisma/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/library";
import { FruitCountCached, FruitFindFirstCached, FruitFindManyCached, FruitFindUniqueCached } from "@services/cached";
import { ResponseFormat, parseAndDecodeParams } from "@utils/FetchConfig";
import { NextRequest, NextResponse } from "next/server";

/**
 * # Fruit Api Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `scripts/generator.ts`
 * - which uses `template/services/api/{{model}}Api.hbs` as base template
 * - to generate api function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type FruitFindFirstProps<T extends Prisma.FruitFindFirstArgs> = Prisma.SelectSubset<T, Prisma.FruitFindFirstArgs>;
type FruitFindFirstResponse<T extends Prisma.FruitFindFirstArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type FruitFindUniqueProps<T extends Prisma.FruitFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.FruitFindUniqueArgs>;
type FruitFindUniqueResponse<T extends Prisma.FruitFindUniqueArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type FruitFindManyProps<T extends Prisma.FruitFindManyArgs> = Prisma.SelectSubset<T, Prisma.FruitFindManyArgs>;
type FruitFindManyResponse<T extends Prisma.FruitFindManyArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type FruitCountProps<T extends Prisma.FruitCountArgs> = Prisma.SelectSubset<T, Prisma.FruitCountArgs>;
type FruitCountResponse<T extends Prisma.FruitCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.FruitCountAggregateOutputType>
        : number;

// ========== Routes ========== //

type RouteResponse<T> = Promise<NextResponse<ResponseFormat<T>>>;

export type FruitRoutes<Input> = {
    /**
     * ## Fruit Find First (API)
     */
    "/fruit/findFirst": <T extends Prisma.FruitFindFirstArgs>() => {
        params: FruitFindFirstProps<T>;
        response: FruitFindFirstResponse<Input extends FruitFindFirstProps<T> ? Input : never>;
    };
    /**
     * ## Fruit Find Unique (API)
     */
    "/fruit/findUnique": <T extends Prisma.FruitFindUniqueArgs>() => {
        params: FruitFindUniqueProps<T>;
        response: FruitFindUniqueResponse<Input extends FruitFindUniqueProps<T> ? Input : never>;
    };
    /**
     * ## Fruit Find Many (API)
     */
    "/fruit/findMany": <T extends Prisma.FruitFindManyArgs>() => {
        params: FruitFindManyProps<T>;
        response: FruitFindManyResponse<Input extends FruitFindManyProps<T> ? Input : never>;
    };
    /**
     * ## Fruit Count (API)
     */
    "/fruit/count": <T extends Prisma.FruitCountArgs>() => {
        params: FruitCountProps<T>;
        response: FruitCountResponse<Input extends FruitCountProps<T> ? Input : never>;
    };
};

// ========== Services ========== //

export const FruitFindFirstApi = async <T extends Prisma.FruitFindFirstArgs>(
    request: NextRequest,
): RouteResponse<FruitFindFirstResponse<T>> => {
    try {
        const params: FruitFindFirstProps<T> = parseAndDecodeParams(request);
        const response: FruitFindFirstResponse<T> = await FruitFindFirstCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: "FruitFindFirstApi -> " + (error as Error).message }, { status: 500 });
    }
};

export const FruitFindUniqueApi = async <T extends Prisma.FruitFindUniqueArgs>(
    request: NextRequest,
): RouteResponse<FruitFindUniqueResponse<T>> => {
    try {
        const params: FruitFindUniqueProps<T> = parseAndDecodeParams(request);
        const response: FruitFindUniqueResponse<T> = await FruitFindUniqueCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: "FruitFindUniqueApi -> " + (error as Error).message }, { status: 500 });
    }
};

export const FruitFindManyApi = async <T extends Prisma.FruitFindManyArgs>(
    request: NextRequest,
): RouteResponse<FruitFindManyResponse<T>> => {
    try {
        const params: FruitFindManyProps<T> = parseAndDecodeParams(request);
        const response: FruitFindManyResponse<T> = await FruitFindManyCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: "FruitFindManyApi -> " + (error as Error).message }, { status: 500 });
    }
};

export const FruitCountApi = async <T extends Prisma.FruitCountArgs>(
    request: NextRequest,
): RouteResponse<FruitCountResponse<T>> => {
    try {
        const params: FruitCountProps<T> = parseAndDecodeParams(request);
        const response: FruitCountResponse<T> = await FruitCountCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: "FruitCountApi -> " + (error as Error).message }, { status: 500 });
    }
};
