import { Prisma } from "@prisma/client/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/client";
import { OrderCountCached, OrderFindFirstCached, OrderFindManyCached, OrderFindUniqueCached } from "@services/cached";
import { decodeParams } from "@utils/url-parsers";
import { NextRequest, NextResponse } from "next/server";
import { ResponseFormat } from "@/solid/solid-config";

/**
 * # Order Api Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/api/{{model}}Api.hbs` as base template
 * - to generate api function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type OrderFindFirstProps<T extends Prisma.OrderFindFirstArgs> = Prisma.SelectSubset<T, Prisma.OrderFindFirstArgs>;
type OrderFindFirstResponse<T extends Prisma.OrderFindFirstArgs> = GetResult<
    Prisma.$OrderPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type OrderFindUniqueProps<T extends Prisma.OrderFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.OrderFindUniqueArgs>;
type OrderFindUniqueResponse<T extends Prisma.OrderFindUniqueArgs> = GetResult<
    Prisma.$OrderPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type OrderFindManyProps<T extends Prisma.OrderFindManyArgs> = Prisma.SelectSubset<T, Prisma.OrderFindManyArgs>;
type OrderFindManyResponse<T extends Prisma.OrderFindManyArgs> = GetResult<
    Prisma.$OrderPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type OrderCountProps<T extends Prisma.OrderCountArgs> = Prisma.SelectSubset<T, Prisma.OrderCountArgs>;
type OrderCountResponse<T extends Prisma.OrderCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.OrderCountAggregateOutputType>
        : number;

// ========== Routes ========== //

type RouteResponse<T> = Promise<NextResponse<ResponseFormat<T>>>;

export type OrderRoutes<Input> = {
    "/solid/order/findFirst": <T extends Prisma.OrderFindFirstArgs>() => {
        params: OrderFindFirstProps<T>;
        response: OrderFindFirstResponse<Input extends OrderFindFirstProps<T> ? Input : never>;
    };
    "/solid/order/findUnique": <T extends Prisma.OrderFindUniqueArgs>() => {
        params: OrderFindUniqueProps<T>;
        response: OrderFindUniqueResponse<Input extends OrderFindUniqueProps<T> ? Input : never>;
    };
    "/solid/order/findMany": <T extends Prisma.OrderFindManyArgs>() => {
        params: OrderFindManyProps<T>;
        response: OrderFindManyResponse<Input extends OrderFindManyProps<T> ? Input : never>;
    };
    "/solid/order/count": <T extends Prisma.OrderCountArgs>() => {
        params: OrderCountProps<T>;
        response: OrderCountResponse<Input extends OrderCountProps<T> ? Input : never>;
    };
};

// ========== Services ========== //

export const OrderFindFirstApi = async <T extends Prisma.OrderFindFirstArgs>(
    request: NextRequest,
): RouteResponse<OrderFindFirstResponse<T>> => {
    try {
        const params: OrderFindFirstProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: OrderFindFirstResponse<T> = await OrderFindFirstCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const OrderFindUniqueApi = async <T extends Prisma.OrderFindUniqueArgs>(
    request: NextRequest,
): RouteResponse<OrderFindUniqueResponse<T>> => {
    try {
        const params: OrderFindUniqueProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: OrderFindUniqueResponse<T> = await OrderFindUniqueCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const OrderFindManyApi = async <T extends Prisma.OrderFindManyArgs>(
    request: NextRequest,
): RouteResponse<OrderFindManyResponse<T>> => {
    try {
        const params: OrderFindManyProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: OrderFindManyResponse<T> = await OrderFindManyCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const OrderCountApi = async <T extends Prisma.OrderCountArgs>(
    request: NextRequest,
): RouteResponse<OrderCountResponse<T>> => {
    try {
        const params: OrderCountProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: OrderCountResponse<T> = await OrderCountCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};
