name: Deploy preview (test)

on:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy test branch in preview
        if: github.ref == 'refs/heads/test'
        runs-on: ubuntu-latest
        steps:
          - name: Trigger Coolify Deploy
            run: |
              curl -X GET "${{ secrets.COOLIFY_API_URL }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_ECO_SERVICE_PREVIEW_UUID }}&force=false&branch=test" \
                -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"
