name: Deploy main
description: On tag on main branch, deploy to production.

on:
    push:
        tags:
          - '*'

jobs:
    deploy:
        name: Deploy to Coolify
        runs-on: ubuntu-latest
        steps:
          - name: Trigger Coolify Deploy
            run: |
              curl -X GET "${{ secrets.COOLIFY_API_URL }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_ECO_SERVICE_UUID }}&force=false&branch=${{ github.ref_name }}" \
                -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"
